### ISSUE TITLE
Not adding </li> tags?

### ISSUE THREAD

**Issue by aingham** [dupkey/bs4navwalker#12]
I was experiencing some problems using this and found that </li> tags were not actually being added. My user case was quite a simple 1 level menu. Chrome browser tools show the tags, but if you actually look at the source, they're not there. I commented out the end_el() function in your code and they are then added again.

**Comment by WeAreDigitalUK** [comment]
This is still an issue, closing </li> tags aren't being added to one level navigation bars.

**Comment by dupkey** [comment]
Thanks for pointing this out. I've updated the `end_el` function. Ref: e88d2d2 The closing `</li>` should be appended now. Since the `<li>` tags are only at depth 0 it should be safe to simplify that condition.

**Comment by WeAreDigitalUK** [comment]
Fantastic, thank you.
