### ISSUE TITLE
Add Sub Menu

### ISSUE THREAD

**Issue by randysmachado** [dupkey/bs4navwalker#15]
**I would like to add Sub-Menu, how do I do this? Can you help me?**

**Comment by dupkey** [comment]
You should be able to use the built-in WordPress menu manager in the admin area to create sub-menus.

**Comment by randysmachado** [comment]
I use the WordPress menu, but only 1 level appears.
Take a look at the images below my menu and note that only 1 level appears

https://prnt.sc/i0y1fr 
https://prnt.sc/i0y2ds

![print-1](https://user-images.githubusercontent.com/25080392/34964412-92cb648e-fa34-11e7-9453-0749a3e18409.jpg)
![print-2](https://user-images.githubusercontent.com/25080392/34964414-930a1ee0-fa34-11e7-91c2-4d2ddbc7cc7c.jpg)

**Comment by dupkey** [comment]
Ok, I understand what you're asking now. Unfortunately, unless something has changed, Bootstrap versions 3+ doesn't support nested dropdowns. Check out this thread: [https://github.com/twbs/bootstrap/issues/21026](https://github.com/twbs/bootstrap/issues/21026)

There are 3rd party solutions to make it work however this particular lib doesn't support anything out of the box. Sorry.
