### ISSUE TITLE
Missing Parent Classes When Child is Active

### ISSUE THREAD

**Issue by RevelationTravis** [dupkey/bs4navwalker#17]
The desired effect is for the parent item to have a class of "active" and/or the default classes that WordPress would assign to a parent menu item when a child is active.

From my very limited preliminary tests, adding the following line of code between lines 63 and 64 of the current navwalker fixes the problem:
$classes[] = ($item->current || $item->current_item_ancestor) ? 'active' : '';

Of course you could choose "current-menu-parent" instead of active (which is what appears on the WordPress TwentySeventeen Theme) or whatever class name you want. My personal preference is active.

**Comment by dupkey** [comment]
"current-menu-parent" is being applied to the parent <li> tag. The "active" class is being applied to nav-link and dropdown-item <a>'s.
