### ISSUE TITLE
Problem with the responsive navbar

### ISSUE THREAD

**Issue by nicolaslagrange** [dupkey/bs4navwalker#2]
Hello,

I try to use your navwalker. It work well in "desktop" but not in xs or sm. The menu don't appear when I click on the toggle button.

Do you have an idea of what's wrong ? 

Thanks for your job,

**Comment by dupkey** [comment]
@nicolaslagrange which version of Bootstrap 4 are you using? I haven't had a chance to test this in alpha.3 yet. Also, have you added the bootstrap.js file to your page?

**Comment by nicolaslagrange** [comment]
I use the alpha 2 for the moment. I added the bootstrap.js file in my page and the toggle button work fine. In mobile devise (phone), when I click on the toggle button, the menu is opening correctly but I don't have any link or item-menu.

**Comment by dupkey** [comment]
I think I'd need to see a code example to troubleshoot the exact issue. Do you have a repository I can pull from?
