### ISSUE TITLE
Titles for links

### ISSUE THREAD

**Issue by LittleHamster** [dupkey/bs4navwalker#21]
Can you add support for titles in the links?

default
```html
<li id="menu-item-12" class="..."><a href="SOME-LINK" class="nav-link active">ITEM</a></li>
```

adding `title` for the links:
```html
<li id="menu-item-12" class="..."><a title="ITEM" href="SOME-LINK" class="nav-link active">ITEM</a></li>
```

**Comment by JeusuDigital** [comment]
It does show them if set in Wordpress under Title Attribute, though I did not want to set them all and just wanted to show the standard title so I made an edit here which has a fallback to the standard title: 

https://github.com/JeusuDigital/bs4navwalker/commit/e4c559819280bda96f6e3fc0e6838c7d6cb96556

**Comment by dupkey** [comment]
For this particular use case I think you should probably fork the repo. I just don't see many nav elements with titles around the net.
