### ISSUE TITLE
CSS classes from menu builder not included when menu intended

### ISSUE THREAD

**Issue by robertandrews** [dupkey/bs4navwalker#8]
The menu builder in the backend has the option to write in a specific CSS class to spit out with a menu item.
Although I have done this, the class name does not get output by bs4navwalker.
The problem is, although the class appears as it should when the menu is a top-level one, it is not included when it is a second-level, intended menu item.

Looks like you need to ensure classes can be displayed when a menu is lower-level.

Version 0.1.

**Comment by robertandrews** [comment]
Thanks for tagging this for enhancement.
When do you imagine the next release?

**Comment by adaprile** [comment]
I was able to solve this problem by replacing line 134 with the following:
`$manual_class = array_values($classes)[0] .' '. 'dropdown-item';`
`$atts ['class']= $manual_class;`

This runs through the '$classes' array and grabs the first item '[0]' which represents the class you add in the WP Menu Admin. It will work on every level after the top. It still includes the 'dropdown-item' class that is being added on this line initially.

**Comment by dupkey** [comment]
Thanks @adaprile that will be in the next release.
